### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Gpx** [Gpx/react-chassis#1]
* [x] Setup travis
* [x] Setup codeclimate
* [x] Setup codecov
* [x] Setup semantic release
* [x] Add prettier
* [ ] Setup deploy
* [ ] Add `Flex`
* [ ] Add https://www.catalog.style/
* [ ] Add `Grid`
* [ ] Add configuration
* [ ] Add `ShowAt`/`HideAt`
* [ ] Add README
